Repository redgold-io/redgold, pull requests merged in 2023-08, with the labels that each got.

#301 Cleanup parts of data store old code
  data/migrations/20220602030202_mnemonic.sql
  src/api/rosetta/handlers.rs
  src/api/rosetta/spec.rs
  src/core/process_transaction.rs
  src/core/transaction.rs
  src/data/data_store.rs
  src/node.rs
  src/util/cli/commands.rs
Labels: debt

#304 Miniscript patch
  schema/Cargo.toml
Labels: bug

#313 Peer connect, drop peers on discovery interval
  data/src/peer.rs
  schema/json_build_config.json
  schema/src/structs.proto
  src/core/discovery.rs
Labels: bug, data-store

#314 Xor distance function, partial stub for sqlite
  data/src/transaction_store.rs
  schema/src/hash.rs
  schema/src/util/mod.rs
  schema/src/util/xor_distance.rs
  src/node.rs
Labels: scaling-performance

#318 Fix explorer
  src/api/explorer/mod.rs
  vue-explorer/src/components/BriefPeer.vue
Labels: bug

#321 Preparation for moving datastore classes to module
  data/Cargo.toml
  data/src/address_block.rs
  data/src/transaction_store.rs
  src/api/rosetta/handlers.rs
  src/api/rosetta/mod.rs
  src/api/rosetta/spec.rs
  src/core/block_formation.rs
  src/data/data_store.rs
  src/data/download.rs
  src/node.rs
  src/trust/rewards.rs
Labels: debt

#322 Switch to stable, comment extism, lto=true and drop optimization to 1
  .github/workflows/ci.yml
  Cargo.toml
  bin/install_build_deps.sh
  executor/Cargo.toml
  executor/src/extism_debug.rs
Labels: bug

#337 Move DS to module
  Cargo.toml
  data/Cargo.toml
  data/src/data_store.rs
  data/src/lib.rs
  src/api/hash_query.rs
  src/api/public_api.rs
  src/api/rosetta/handlers.rs
  src/api/rosetta/mod.rs
  src/api/rosetta/spec.rs
  src/core/block_formation.rs
  src/core/observation.rs
  src/core/peer_rx_event_handler.rs
  src/core/process_transaction.rs
  src/core/relay.rs
  src/core/transaction.rs
  src/data/block_store.rs
  src/data/data_store.rs
  src/data/download.rs
  src/data/mod.rs
  src/gui/app_loop.rs
  src/node.rs
  src/node_config.rs
  src/util/cli/arg_parse_config.rs
  src/util/cli/commands.rs
  src/util/cli/data_folder.rs
  src/wallet/mod.rs
Labels: debt

#341 Missing dev dependency
  .github/workflows/ci.yml
Labels: bug

#386 Explorer bug
  schema/src/resources/example_servers
  schema/src/servers.rs
  src/api/explorer/mod.rs
  src/util/cli/args.rs
  src/util/cli/commands.rs
Labels: bug

#387 GUI main error, cleanup pending fix
  schema/src/servers.rs
  src/core/process_transaction.rs
  src/util/cli/arg_parse_config.rs
  src/util/cli/data_folder.rs
Labels: bug
