Repository redgold-io/redgold, pull requests merged in 2023-07, with the labels that each got.

#249 Update doc links
  docs/app.config.ts
  docs/components/Logo.vue
  src/infra/deploy.rs
  vue-explorer/src/components/Header.vue
Labels: docs

#263 Fix deploy scripts for CLI
  src/api/public_api.rs
  src/infra/deploy.rs
  src/infra/mod.rs
  src/node.rs
  src/resources/infra/ops_services/services-all.yml
  src/util/cli/arg_parse_config.rs
  src/util/cli/args.rs
  src/util/cli/commands.rs
Labels: bug

#265 Fix CI Mac nightly toolchain, bump version staging
  .github/workflows/ci.yml
  Cargo.toml
  bin/install_build_deps.sh
  data/Cargo.toml
  data/src/peer.rs
  executor/Cargo.toml
  schema/Cargo.toml
  schema/src/peers.rs
  src/core/discovery.rs
  src/core/peer_event_handler.rs
  src/core/peer_rx_event_handler.rs
  src/lib.rs
  src/multiparty/initiate_mp.rs
  src/multiparty/watcher.rs
  src/node.rs
  src/node_config.rs
  src/util/trace_setup.rs
Labels: bug

#267 Working multiparty fix
  schema/json_build_config.json
  schema/src/multiparty.rs
  schema/src/structs.proto
  src/core/relay.rs
  src/infra/deploy.rs
  src/multiparty/gg20_keygen.rs
  src/multiparty/gg20_signing.rs
  src/multiparty/gg20_sm_client.rs
  src/multiparty/gg20_sm_manager.rs
  src/multiparty/initiate_mp.rs
  src/node.rs
  src/node_config.rs
  src/util/cli/args.rs
  src/util/cli/commands.rs
Labels: bug

#268 Strange recursion error again?
  .github/workflows/ci.yml
Labels: bug

#270 Recursion error
  .github/workflows/ci.yml
Labels: bug

#272 Fix hash signature on watcher init
  src/multiparty/watcher.rs
Labels: bug

#273 Disable ansi colors
  src/util/trace_setup.rs
Labels: bug

#278 Fix prometheus dynamic
  src/infra/deploy.rs
  src/resources/infra/ops_services/services-all.yml
  src/util/cli/args.rs
Labels: bug

#282 Port fixes for deploy script
  src/infra/deploy.rs
  src/resources/infra/ops_services/services-all.yml
  src/util/cli/args.rs
Labels: bug

#279 Add total utxo/obs/tx counts
  data/Cargo.toml
  data/src/observation_store.rs
  data/src/transaction_store.rs
  src/data/data_store.rs
  src/node.rs
  src/util/metrics_registry.rs
Labels: observability
